### ISSUE TITLE
Missing deriving for newtypes and core objects

### ISSUE THREAD

**Issue by RaitoBezarius** [DeterminateSystems/bootspec#67]
- `GenerationV1` should implement `Clone`
- `SpecialisationName` should implement `Display`

**Comment by cole-h** [comment]
FWIW, you can get the wrapped `String` of `SpecialisationName` by using `var.0` -- it's `pub`lic, so that should work fine.

Not to say I object to implementing `Display`, just that that's possible for newtypes that `pub`licize their wrapped type.
