### ISSUE TITLE
Schema filename is inconsistent

### ISSUE THREAD

**Issue by RaitoBezarius** [DeterminateSystems/bootspec#70]
I think it's `boot.v1.json` but I think we decided it will be `boot.json` anyway?

**Comment by cole-h** [comment]
Ah, indeed -- this changed in the RFC here: [NixOS/rfcs@`2f239c9` (#125)](https://github.com/NixOS/rfcs/pull/125/commits/2f239c97826125b2b62adfeb7b5b32e77a8419d4), when we decided to use `{"v1": { ... }}` in `boot.json` as opposed to `{"schemaVersion":1, ...}` in `boot.v1.json`. The new approach means that consumers don't need to parse the file blindly to be able to check if the `schemaVersion` indeed matches the filename / expected version, but can instead just rely on "if the `v1` key exists, then we'll be getting a `v1` document".

**Comment by cole-h** [comment]
Fixed in https://github.com/DeterminateSystems/bootspec/pull/73.
